### PR TITLE
Remove static initializer

### PR DESCRIPTION
**Pull request by Adelrisk**
Updates to RobiVM make the initialization of the framework with a call to `rvmInstantiateFramework` obsolete.

For improved integration in Apps, the emitted factory method is marked as deprecated in the generated header file. These changes also ensure that other deprecated methods/classes are also marked as deprecated in the generated header files.

### CODE REVIEW

**Review by sake — COMMENTED** [review]
I can't say much about the changes as I have no means to test the result on my machine and my swift knowlegde is also quite limited.

But it builds, so ...

**Comment by Adelrisk** [comment]
> But it builds, so ...

Luckily, the situation is not too bad. The example project generates a "reviewable" jar and header files. @legion151 claims it works as expected.

**Comment by sake** [comment]
> Luckily, the situation is not too bad. The example project generates a "reviewable" jar and header files. @legion151 claims it works as expected.

That's what I was looking at besides inspecting the code.

**Comment by legion151** [comment]
i checked and tested. Will merge.

**Pull request merged**
